### ISSUE TITLE
bug in 2.79

### ISSUE THREAD

**Issue by brothermechanic** [hophead-ninja/perfect_shape#1]
hello, great script, thank you

but now it dont works

```
Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/addons/perfect_shape/operators.py", line 179, in execute
    cache_verts = get_cache(self.as_pointer(), "shape_verts_{}".format(loop_idx))
  File "/usr/share/blender/2.79/scripts/addons/perfect_shape/utils.py", line 19, in get_cache
    raise CacheException("No key cache")
perfect_shape.utils.CacheException: No key cache

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/share/blender/2.79/scripts/addons/perfect_shape/operators.py", line 574, in invoke
    ret = self.execute(context)
  File "/usr/share/blender/2.79/scripts/addons/perfect_shape/operators.py", line 195, in execute
    shape_verts = bmesh.ops.create_circle(shape_bm, segments=shape_segments, diameter=diameter)
TypeError: create_circle: keyword "diameter" is invalid for this operator

location: <unknown location>:-1
```
may be you can fix it

**Comment by Zuorion** [comment]
you need change diameter to radius/2

or use fork: https://github.com/crantisz/perfect_shape

**Comment by brothermechanic** [comment]
Works!
Thank you!
